### ISSUE TITLE
Filtering a nullable property will throw an exception

### ISSUE THREAD

**Issue by Roman1991** [AutoMapper/AutoMapper.Extensions.OData#11]
The object structure: 
```
user
 - details (navigation proepty)
   - type (nullable enum) 
      - Customer
      - Employee
      - Test
```

The filter query:
`details/type eq null`

Get the collection:
`ICollection<Dto> result = await sourceQueryable.GetAsync(mapper, odataOptions);`

It will throw the following exception:

```
System.ArgumentException: Argument types do not match
   at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse)
   at AutoMapper.Extensions.ExpressionMapping.XpressionMapperVisitor.<VisitConditional>g__DoVisitConditional|22_0(Expression test, Expression ifTrue, Expression ifFalse, <>c__DisplayClass22_0& )
   at AutoMapper.Extensions.ExpressionMapping.XpressionMapperVisitor.VisitConditional(ConditionalExpression c)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at AutoMapper.Extensions.ExpressionMapping.XpressionMapperVisitor.VisitUnary(UnaryExpression node)
   at AutoMapper.Extensions.ExpressionMapping.XpressionMapperVisitor.VisitBinary(BinaryExpression node)
...
```

**Comment by BlaiseD** [comment]
Easier to help with a failing sample - maybe add an example to the [tests.](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/master/AutoMapper.OData.EFCore.Tests/AllTests.cs) if you need oData.

Or add a [repo](https://github.com/Roman1991?tab=repositories).
