### ISSUE TITLE
Not working filter operator in on enums

### ISSUE THREAD

**Issue by petrkasnal** [AutoMapper/AutoMapper.Extensions.OData#183]
Hi,

i was try filter my enum values with in operator.

`/entitites?$filter=((MyType in ('Started')))`

And i have this error. When i try it on string or int it's working normally. But in enum it's problem. Equal on enum is normally working.
Thanks

**Message:**
No generic method 'Contains' on type 'System.Linq.Enumerable' is compatible with the supplied type arguments and arguments. No type arguments should be provided if the method is non-generic. 

**Stack trace**
   at System.Linq.Expressions.Expression.FindMethod(Type type, String methodName, Type[] typeArgs, Expression[] args, BindingFlags flags)
   at System.Linq.Expressions.Expression.Call(Type type, String methodName, Type[] typeArguments, Expression[] arguments)
   at AutoMapper.Extensions.ExpressionMapping.MapperExtensions.<MapExpression>g__MapBody|8_1[TDestDelegate](Dictionary`2 typeMappings, XpressionMapperVisitor visitor, <>c__DisplayClass8_0`1& )
   at AutoMapper.Extensions.ExpressionMapping.MapperExtensions.MapExpression[TDestDelegate](IConfigurationProvider configurationProvider, LambdaExpression expression, Type typeSourceFunc, Type typeDestFunc, Func`3 getVisitor, Func`2 shouldConvertMappedBodyToDestType)
   at AutoMapper.Extensions.ExpressionMapping.MapperExtensions.MapExpression[TDestDelegate](IMapper mapper, LambdaExpression expression, Func`3 getVisitor, Func`2 shouldConvertMappedBodyToDestType)
   at AutoMapper.Extensions.ExpressionMapping.MapperExtensions.MapExpression[TDestDelegate](IMapper mapper, LambdaExpression expression)
   at AutoMapper.AspNet.OData.QueryableExtensions.GetQuery[TModel,TData](IQueryable`1 query, IMapper mapper, Expression`1 filter, Expression`1 queryFunc, IEnumerable`1 includeProperties, ProjectionSettings projectionSettings)
   at AutoMapper.AspNet.OData.QueryableExtensions.GetQueryable[TModel,TData](IQueryable`1 query, IMapper mapper, ODataQueryOptions`1 options, QuerySettings querySettings, Expression`1 filter)
   at AutoMapper.AspNet.OData.QueryableExtensions.GetQuery[TModel,TData](IQueryable`1 query, IMapper mapper, ODataQueryOptions`1 options, QuerySettings querySettings)
   at Application.Handlers.All.AllQueryHandler.Handle(AllQuery request, CancellationToken cancellationToken) in C:\user\workspace\..... 43
   at Framework.Mediator.Behaviors.AuthorizationBehaviour`2.<Handle>d__3.MoveNext()

**Comment by BlaiseD** [comment]
Enums should work [e.g](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/b44c99cfa0afdb2a1ab5a7f4d310ea0ae3f42d90/ExpressionBuilder.Tests/FilterTests.cs#L3189). 

Make sure you're using [this version](https://www.nuget.org/packages/AutoMapper.Extensions.ExpressionMapping/) of the expression mapping library.  Otherwise post a repro we can execute and recreate the exception.
